modify import-tfstate script
- added function to check required params
- capturing datadog api response to give better error messages in the task

Signed-off-by: Izabela Gomes <igomes@pivotal.io>

diff --git a/tasks/scripts/import-tfstate b/tasks/scripts/import-tfstate
--- a/tasks/scripts/import-tfstate
+++ b/tasks/scripts/import-tfstate
@@ -1,18 +1,58 @@
 #!/bin/bash
 
+set -e
 WORKDIR=$PWD
+check_required_parameters() {
+  if [[ -z $DATADOG_API_KEY ]]; then
+    echo "DATADOG_API_KEY environment variable must be specified"
+    exit 1
+  fi
+
+  if [[ -z $DATADOG_APP_KEY ]]; then
+    echo "DATADOG_APP_KEY environment variable must be specified"
+    exit 1
+  fi
+
+  if [[ -z $DASHBOARD_TITLE ]]; then
+    echo "DASHBOARD_TITLE environment variable must be specified"
+    exit 1
+  fi
+
+  if [[ -z $RESOURCE_ADDRESS ]]; then
+    echo "RESOURCE_ADDRESS environment variable must be specified"
+    exit 1
+  fi
+
+  if [[ -z $RESOURCE_ADDRESS_SYSSTATS ]]; then
+    echo "RESOURCE_ADDRESS_SYSSTATS environment variable must be specified"
+    exit 1
+  fi
+}
+
+check_required_parameters
 
 # Use Datadog web-api to find dashboard ID based on the dashboard title
-curl -X GET https://api.datadoghq.com/api/v1/dashboard \
+api_response=$(curl -X GET https://api.datadoghq.com/api/v1/dashboard \
 -H "Content-Type: application/json" \
 -H "DD-API-KEY: ${DATADOG_API_KEY}" \
 -H "DD-APPLICATION-KEY: ${DATADOG_APP_KEY}" \
--s -o all-dashboards.json
+-w "%{http_code}\n" \
+-s -o all-dashboards.json)
 
-DASHBOARD_ID=$(jq -r --arg TITLE "$DASHBOARD_TITLE" '.dashboards[] | select(.title == $TITLE) | .id' all-dashboards.json)
+if [[ $api_response -lt 200 || $api_response -ge 300 ]]; then
+  echo "Error response from Datadog API: HTTP $api_response"
+  exit 1
+fi
 
 DASHBOARD_TITLE_SYSSTATS="$DASHBOARD_TITLE - System Stats"
+
+DASHBOARD_ID=$(jq -r --arg TITLE "$DASHBOARD_TITLE" '.dashboards[] | select(.title == $TITLE) | .id' all-dashboards.json)
 DASHBOARD_ID_SYSSTATS=$(jq -r --arg TITLE "$DASHBOARD_TITLE_SYSSTATS" '.dashboards[] | select(.title == $TITLE) | .id' all-dashboards.json)
+
+if [ -z "$DASHBOARD_ID" ] && [ -z "$DASHBOARD_ID_SYSSTATS" ]; then
+  echo "No dashboards named '$DASHBOARD_TITLE' or '$DASHBOARD_TITLE_SYSSTATS' were found"
+  exit 1
+fi
 
 # Workaround to use `terraform import` command with modules and dynamic value assignment
 cd greenpeace/terraform
